### ISSUE TITLE
Stemcell - Research Group

### ISSUE THREAD

**Issue by sztamas** [muccg/bpa-ingest#19]
BPA requested Research Group to be added to the project overview page.

Where is research group coming from and at what stage? Does it have to be added to CKAN only or to the Tracker Django models as well?

When done add a ticket to bpa-metadata with details so the Project Overview page can be updated.

**Comment by grahame** [comment]
> Hi Shian
> 
> Just to confirm I've been able to ingest the data. Thanks for your help.
> 
> Some feedback on this upload:
> 
> Zip archive:
> Unfortunately our (Linux based) tools were not able to decompress the Zip file. We saw that it was made on an Apple Mac, and we were able to use a Mac to decompress the data. In future, could the data be packed into a "tar" rather than using Zip? Let us know if you need support using tar.
> 
> File naming:
> The file "SOX10pos_WEHI_HHMYYBGXY_checksums" should have been named "SOX10pos_WEHI_HHMYYBGXY_checksums.md5".
> We've renamed at our end.
> It should have the same prefix as the metadata spreadsheet, and end with "_checksums.md5".
> 
> MD5 format:
> We support this format for MD5 files:
> bfca865c9fc62b672e489e122d35db79  24732-25115_PE_550bp_Stemcells_WEHI_HHMYYBGXY_NoIndex_L001_R1.fastq.gz
> 098148cec2a1ae2461ac2d57ff64aca6  24732-25115_PE_550bp_Stemcells_WEHI_HHMYYBGXY_NoIndex_L001_R2.fastq.gz
> 
> This maches the output of the "md5sum" program, standard on Linux systems.
> We can also support the format of output produces by the "md5" program on BSD/Mac systems, eg.
> 
> MD5 (24732-25115_PE_550bp_Stemcells_WEHI_HHMYYBGXY_NoIndex_L001_R1.fastq.gz) = bfca865c9fc62b672e489e122d35db79
> 
> I've corrected this at our end, but please use one of these two formats for future datasets.
> 
> MD5 all files:
> Please include all files in the MD5 file, including any spreadsheets.
> I've fixed this at our end (as you gave us a checksum for the Zip archive, we know the XLSX files came through OK.)
> 
> Thanks for working with us to get this data ingested.
> 
> Cheers, and have a good weekend
>

**Comment by grahame** [comment]
Ticket moved into bpa-archive-ops.
