### ISSUE TITLE
Stemcell Metabolomics omics field set incorrectly to transcriptomics

### ISSUE THREAD

**Issue by sztamas** [muccg/bpa-ingest#20]
Looks like a copy'n'paste error:

https://github.com/muccg/bpa-ingest/blob/20558255fb564c75b3d5e2c1a20b2b1723e9438a/bpaingest/projects/stemcells/ingest.py#L412

"transcriptomics" should be "metabolomics".

**Comment by sztamas** [comment]
OPS ticket for updating existing data:

https://github.com/muccg/ops/issues/1168

**Comment by grahame** [comment]
Resolved.
